# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbca8a0622ccacbb1d4556b18a163428049a67c0bad07dcaf6219b5a96530d396391cf6a20a7e4c1bc3dc59f21878f2311bf6f72e722e3b3c60e5d5952a76530

test:
  secret_key_base: 9b911008dea7ad3b7645f2903fc9ea9818e7eb62321674e62f47338a21666d4934a748c2aecb9265e8aee8f7e3b7cbae92c15c48885a1cdb6a16ff56461c57ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
